apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: read-app
spec:
  template:
    metadata:
      annotations:  
        dapr.io/app-id: read-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true" 
        dapr.io/metrics-port: "9092"
        autoscaling.knative.dev/min-scale: "{{ .Values.minScale }}"
{{ if .Values.inVcluster }}   
        dapr.io/disable-builtin-k8s-secret-store: "true"     
{{- end}}
    spec:
      containerConcurrency: 0
      containers:
        - image: docker.io/salaboy/read-values-29641880cfce629a7bb375adac757e79@sha256:f11255260ad9d9593b97d513ba6e9e6526bff705be0932db23048fa002f5613a
          name: user-container
          env: 
          - name: STATE_STORE_NAME
            value: statestore
          livenessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/liveness
              port: 8080